### ISSUE TITLE
Error on server on windows

### ISSUE THREAD

**Issue by ErliSoares** [orzih/mkdocs-extra-sass-plugin#2]
Error when server:  `ModuleNotFoundError: No module named 'livereload'`

<details>
<summary>log</summary>

```
$ mkdocs serve
INFO     -  Building documentation...
Traceback (most recent call last):
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\commands\serve.py", line 54, in serve
    config = builder()
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\commands\serve.py", line 35, in builder
    config = load_config(
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\config\base.py", line 224, in load_config
    errors, warnings = cfg.validate()
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\config\base.py", line 108, in validate
    run_failed, run_warnings = self._validate()
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\config\base.py", line 63, in _validate
    self[key] = config_option.validate(value)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\config\config_options.py", line 130, in validate
    return self.run_validation(value)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\config\config_options.py", line 636, in run_validation       
    plgins[item] = self.load_plugin(item, cfg)
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\config\config_options.py", line 649, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs_extra_sass_plugin\plugin.py", line 10, in <module>
    from livereload import Server
ModuleNotFoundError: No module named 'livereload'
```

</details>

> Solved by installing `pip install livereload`

**Comment by orzih** [comment]
refs: https://github.com/mkdocs/mkdocs/pull/2477
